# Generated by Django 4.2 on 2024-11-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('erkek', 'Erkek'), ('kadın', 'kadın'), ('belirtilmemiş', 'Belirtilmemiş')], max_length=100, null=True),
        ),
    ]
